[project]
name = "esp32"
version = "0.1.0"
description = "Collection of esp32 projects"
authors = [
    {name = "bengabp",email = "bengabdev4@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "adafruit-ampy (>=1.1.0,<2.0.0)",
    "micropy-cli (>=4.2.2,<5.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
